# Site settings
title: "Maths and ..."
email: goetz.pfeiffer@nuigalway.ie
description: > # this means to ignore newlines until "baseurl:"
  Seminar talks and other notes ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://schmidt.nuigalway.ie" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  gpfeiffer
disqus: gpfeiffer
#google_analytics: UA-72475442-1

# Build settings
markdown: kramdown
future: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: "Götz Pfeiffer"
      layout: post
      category: notes
